import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import { Sidebar, Discover } from "./components";

export default function Home() {
  return (
    <div className="h-auto select-none">
      <Head>
        <title>Elementee.</title>
        <link rel="icon" href="../public/svg/Logo.js" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="h-[100%] grid grid-cols-10">
        <Sidebar />
        <Discover />
      </main>
    </div>
  );
}
